length = input("Length = ")
width = input("Width = ")
area = int(length) * int(width)
circumference = 2*int(width) + 2*int(length)
print(f"Area of the rectangle: {area}")
print(f"Circumference of the rectangle: {circumference}")
